name: Build

on:
- push

jobs:
  listVersions:
    name: List Versions (this could be a build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List Versions
        shell: pwsh
        run: |
          Get-Content 'Project 1/version.txt'
          Get-Content 'Project 2/version.txt'
          Get-Content 'Project 3/version.txt'
